Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
start sleep
end sleep
Got virus message
Bashlite was restarted after 120 seconds
start sleep
end sleep
Got virus message
Bashlite was restarted after 120 seconds
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
start sleep
end sleep
Got virus message
Bashlite was restarted after 120 seconds
start sleep
end sleep
Got virus message
Bashlite was restarted after 120 seconds
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message

Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused

















Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message

Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/MalwareOne/workspace/monitoring/sendToDeployerClient.py", line 36, in <module>
    ownSocket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
Got virus message
